apiVersion: v1
kind: Pod
metadata:
  name: gke-unit-testing
spec:
  containers:
  - name: unit-testing
    image: gcr.io/automatictrainingcicd/unit-testing:latest
    env:
      - name: gmail_password
        valueFrom:
          secretKeyRef:
            name: gmail-secrets
            key: gmail_password
      - name: email_address
        value: svirahonda@gmail.com